//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sample
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sample()
        {
            this.Vote = new HashSet<Vote>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public string Title { get; set; }
        public string Content_Path { get; set; }
        public string Url { get; set; }
        public string Location { get; set; }
        public string Meta_Value { get; set; }
        public Nullable<int> Count_Up { get; set; }
        public Nullable<int> Count_Down { get; set; }
        public Nullable<System.DateTime> Last_Update { get; set; }
        public Nullable<int> Lifetime { get; set; }
        public Nullable<System.DateTime> Posted_on { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> MusicGenreID { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vote> Vote { get; set; }
        public virtual MusicGenre MusicGenre { get; set; }
    }
}
