//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleMag
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Sample = new HashSet<Sample>();
            this.Vote = new HashSet<Vote>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Profile_Name { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public Nullable<int> Phone { get; set; }
        public Nullable<int> Language_Preference_ID { get; set; }
        public string Timezone { get; set; }
        public byte[] Profile_Picture { get; set; }
        public string User_Bio { get; set; }
        public string Url { get; set; }
        public Nullable<int> User_Status_ID { get; set; }
        public Nullable<int> User_Type_ID { get; set; }
        public Nullable<int> Vote_Count_Up { get; set; }
        public Nullable<int> Vote_Count_Down { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sample> Sample { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vote> Vote { get; set; }
    }
}
